name: seiya

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - static/images/
    - static/images/icons/
    - static/images/common/
    - static/images/common/tools/
    - static/images/placeholder/
    - static/images/console/

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.5
  path: ^1.9.1
  flutter_svg: ^2.1.0
  uuid: ^4.5.1
  validators: ^3.0.0
  split_view: ^3.2.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  material_symbols_icons: ^4.2815.0
  flutter_screenutil: ^5.9.3
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  markdown: ^7.3.0
  loading_indicator: ^3.1.1
  go_router: ^15.1.1
  logger: ^2.5.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  assorted_layout_widgets: ^11.0.0
  webview_flutter: ^4.13.0
  seiyapkg:
    path: plugins/seiyapkg
  ffi: ^2.1.4

dev_dependencies:
  flutter_lints:
  json_serializable: ^6.9.5
  build_runner:
  riverpod_generator: ^2.6.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
